###
POST http://localhost:5000/api/v3/series/serie HTTP/1.1
Content-Type: application/json

{
    "serie": "Prueba8",
    "number_seasons": 1,
    "original_lenguage": "ingles",
    "features_seasons": [{
        "season_number":1,
        "season_name": "Last",
        "premier_date": "2022-03-31",
        "cast": ["Mateo", "Pablo", "Juan"],
        "episodes": [{
            "episode_name": "Green",
            "time_duration": 35
      }]
    }]
}

###
GET http://localhost:5000/api/v3/series HTTP/1.1

###
GET http://localhost:5000/api/v3/series/6245a68675a8fcd9d9102a4f  HTTP/1.1


//Busqueda por la fecha de estreno de la temporada
###
GET http://localhost:5000/api/v3/series/searchDate/2022-03-29 HTTP/1.1

//Busqueda por el nombre del actor
###
GET http://localhost:5000/api/v3/series/searchActor/Mateo  HTTP/1.1

###
PUT http://localhost:5000/api/v3/series/6245a68675a8fcd9d9102a4d HTTP/1.1
Content-Type: application/json

{
    "serie": "prueba5",
    "number_seasons": 1,
    "original_lenguage": "español",
    "features_seasons": [{
        "season_number":1,
        "season_name": "Patron",
        "premier_date": "2022-03-31",
        "cast": ["Mateo", "Pablo", "Juan"],
        "episodes": [{
            "episode_name": "Green",
            "time_duration": 35
      }]
    }]
}

###
DELETE  http://localhost:5000/api/v3/series/6245a68675a8fcd9d9102a4d HTTP/1.1